"""Version constants and deterministic confidence policy for entity resolution."""

ENGINE_VERSION = "1.0"
POLICY_VERSION = "1.0"

# Deterministic merge confidence by identity key strength.
CONFIDENCE_FILE_HASH = 1.00
CONFIDENCE_EMAIL = 0.98
CONFIDENCE_PHONE = 0.97
CONFIDENCE_QR = 0.95
CONFIDENCE_SIGNATURE = 0.92
CONFIDENCE_LOCATION = 0.90
CONFIDENCE_CAMERA = 0.90
CONFIDENCE_DEVICE = 0.90
CONFIDENCE_IP = 0.90
CONFIDENCE_DOMAIN = 0.88
CONFIDENCE_WEBSITE = 0.88
CONFIDENCE_CRYPTO_WALLET = 0.94
CONFIDENCE_BANK_ACCOUNT = 0.93
CONFIDENCE_DOCUMENT_ID = 0.85
CONFIDENCE_LOGO = 0.86
CONFIDENCE_MEDIA = 0.80
CONFIDENCE_CREATOR = 0.70
CONFIDENCE_ADDRESS = 0.75
CONFIDENCE_RELATIONSHIP_DEFAULT = 0.80
