import { useState } from "react";

import type { ReviewApproval } from "../../types/caseReview";
import { Badge } from "../ui/Badge";
import { Button } from "../ui/Button";
import { Input } from "../ui/Input";
import { Panel } from "../ui/Panel";
import { Select } from "../ui/Select";

interface ApprovalPanelProps {
  approvals: ReviewApproval[];
  requiredRoles: string[];
  onSubmit?: (payload: {
    reviewer: string;
    approver_role: string;
    decision: string;
    comments: string;
  }) => void;
  submitting?: boolean;
}

const ROLES = [
  "TECHNICAL_REVIEWER",
  "FORENSIC_REVIEWER",
  "LEAD_INVESTIGATOR",
  "CASE_SUPERVISOR",
] as const;

const DECISIONS = [
  "APPROVED",
  "REJECTED",
  "CHANGES_REQUESTED",
  "DEFERRED",
] as const;

export function ApprovalPanel({
  approvals,
  requiredRoles,
  onSubmit,
  submitting,
}: ApprovalPanelProps) {
  const [reviewer, setReviewer] = useState("investigator");
  const [role, setRole] = useState<string>(ROLES[0]);
  const [decision, setDecision] = useState<string>("APPROVED");
  const [comments, setComments] = useState("");

  return (
    <Panel
      description="Explicit multi-role approvals. Never auto-generated by AI."
      title="Approval Chain"
    >
      <div className="space-y-4 p-4">
        <div className="flex flex-wrap gap-2 text-xs text-slate-500">
          Required:{" "}
          {(requiredRoles.length ? requiredRoles : ROLES).map((item) => (
            <Badge key={item} tone="neutral">
              {item}
            </Badge>
          ))}
        </div>

        {onSubmit ? (
          <div className="grid gap-2 sm:grid-cols-2">
            <label className="block text-xs text-slate-400">
              Reviewer
              <Input
                className="mt-1"
                onChange={(event) => setReviewer(event.target.value)}
                value={reviewer}
              />
            </label>
            <label className="block text-xs text-slate-400">
              Role
              <Select
                className="mt-1"
                onChange={(event) => setRole(event.target.value)}
                value={role}
              >
                {ROLES.map((item) => (
                  <option key={item} value={item}>
                    {item}
                  </option>
                ))}
              </Select>
            </label>
            <label className="block text-xs text-slate-400">
              Decision
              <Select
                className="mt-1"
                onChange={(event) => setDecision(event.target.value)}
                value={decision}
              >
                {DECISIONS.map((item) => (
                  <option key={item} value={item}>
                    {item}
                  </option>
                ))}
              </Select>
            </label>
            <label className="block text-xs text-slate-400">
              Comments
              <Input
                className="mt-1"
                onChange={(event) => setComments(event.target.value)}
                value={comments}
              />
            </label>
            <Button
              className="sm:col-span-2"
              disabled={submitting}
              onClick={() =>
                onSubmit({
                  reviewer,
                  approver_role: role,
                  decision,
                  comments,
                })
              }
              size="sm"
            >
              Record approval
            </Button>
          </div>
        ) : null}

        {approvals.length === 0 ? (
          <p className="text-xs text-slate-500">No approvals recorded.</p>
        ) : (
          approvals.map((item) => (
            <div
              className="border-b border-slate-800/80 pb-2 text-xs last:border-0"
              key={item.id ?? `${item.approver_role}-${item.created_at}`}
            >
              <div className="flex flex-wrap gap-2">
                <Badge tone="cyan">{item.approver_role}</Badge>
                <Badge tone="neutral">{item.decision}</Badge>
                <span className="text-slate-400">{item.reviewer}</span>
              </div>
              {item.comments ? (
                <p className="mt-1 text-slate-500">{item.comments}</p>
              ) : null}
            </div>
          ))
        )}
      </div>
    </Panel>
  );
}
