"""Version constants and deterministic scoring policy for correlation."""

ENGINE_VERSION = "1.0"
POLICY_VERSION = "1.0"

# Exact-match / high-fidelity scores (deterministic).
SCORE_SAME_HASH = 1.00
SCORE_SAME_EMAIL = 0.98
SCORE_SAME_PHONE = 0.97
SCORE_SAME_QR = 0.95
SCORE_SAME_SIGNATURE = 0.92
SCORE_SAME_LOCATION = 0.90
SCORE_SAME_CAMERA = 0.90
SCORE_SAME_DEVICE = 0.90
SCORE_SAME_AUDIO_SPEAKER = 0.88
SCORE_SAME_LOGO = 0.86
SCORE_SAME_DOCUMENT = 0.85
SCORE_SHARED_IDENTIFIER = 0.82
SCORE_SHARED_METADATA = 0.80
SCORE_TEMPORAL_OVERLAP = 0.70
SCORE_SIMILAR_FILENAME = 0.45

# Confidence mirrors score for exact matches; soft matches use lower confidence.
CONFIDENCE_EXACT = 1.00
CONFIDENCE_STRONG = 0.95
CONFIDENCE_MODERATE = 0.80
CONFIDENCE_WEAK = 0.60
