"""Deterministic policy for Phase 9D decision support."""

from __future__ import annotations

DS_ENGINE_VERSION = "9d.1.0"
DS_POLICY_VERSION = "1.0"

PRIORITY_THRESHOLDS = {"HIGH": 0.75, "MEDIUM": 0.45}

TASK_BASE_PRIORITY: dict[str, float] = {
    "ACQUIRE_ORIGINAL_EVIDENCE": 0.92,
    "VERIFY_METADATA": 0.70,
    "RUN_SIGNATURE_VERIFICATION": 0.78,
    "REVIEW_AI_CONFLICT": 0.88,
    "REVIEW_TIMELINE_CONFLICT": 0.90,
    "COMPARE_RELATED_EVIDENCE": 0.72,
    "VALIDATE_CORRELATION": 0.74,
    "REVIEW_KNOWLEDGE_GRAPH": 0.60,
    "COMPLETE_CHAIN_OF_CUSTODY": 0.86,
    "REVIEW_OCR": 0.65,
    "VALIDATE_REPORT": 0.68,
    "MANUAL_EXPERT_REVIEW": 0.80,
    "CLOSE_INVESTIGATION": 0.55,
}

TASK_STAGE: dict[str, str] = {
    "ACQUIRE_ORIGINAL_EVIDENCE": "COLLECT",
    "VERIFY_METADATA": "VERIFY",
    "RUN_SIGNATURE_VERIFICATION": "VERIFY",
    "REVIEW_AI_CONFLICT": "REVIEW",
    "REVIEW_TIMELINE_CONFLICT": "REVIEW",
    "COMPARE_RELATED_EVIDENCE": "COMPARE",
    "VALIDATE_CORRELATION": "CORRELATE",
    "REVIEW_KNOWLEDGE_GRAPH": "REVIEW",
    "COMPLETE_CHAIN_OF_CUSTODY": "COLLECT",
    "REVIEW_OCR": "AI_ANALYSIS",
    "VALIDATE_REPORT": "REPORT",
    "MANUAL_EXPERT_REVIEW": "REVIEW",
    "CLOSE_INVESTIGATION": "COMPLETE",
}

TASK_EFFORT_HOURS: dict[str, float] = {
    "ACQUIRE_ORIGINAL_EVIDENCE": 4.0,
    "VERIFY_METADATA": 1.0,
    "RUN_SIGNATURE_VERIFICATION": 1.5,
    "REVIEW_AI_CONFLICT": 2.0,
    "REVIEW_TIMELINE_CONFLICT": 2.0,
    "COMPARE_RELATED_EVIDENCE": 2.5,
    "VALIDATE_CORRELATION": 1.5,
    "REVIEW_KNOWLEDGE_GRAPH": 1.0,
    "COMPLETE_CHAIN_OF_CUSTODY": 1.5,
    "REVIEW_OCR": 1.0,
    "VALIDATE_REPORT": 2.0,
    "MANUAL_EXPERT_REVIEW": 3.0,
    "CLOSE_INVESTIGATION": 0.5,
}

# Recommendation code → task type mapping
REC_TO_TASK: dict[str, str] = {
    "ACQUIRE_ORIGINAL_MEDIA": "ACQUIRE_ORIGINAL_EVIDENCE",
    "OBTAIN_DEVICE_METADATA": "VERIFY_METADATA",
    "VERIFY_DIGITAL_SIGNATURE": "RUN_SIGNATURE_VERIFICATION",
    "REVIEW_CONFLICTING_AI": "REVIEW_AI_CONFLICT",
    "INVESTIGATE_TIMELINE_INCONSISTENCY": "REVIEW_TIMELINE_CONFLICT",
    "COMPARE_KNOWN_EVIDENCE": "COMPARE_RELATED_EVIDENCE",
    "RUN_IMAGE_COMPARISON": "COMPARE_RELATED_EVIDENCE",
    "VERIFY_CHAIN_OF_CUSTODY": "COMPLETE_CHAIN_OF_CUSTODY",
    "RUN_OCR": "REVIEW_OCR",
    "RUN_AI_ANALYSIS": "MANUAL_EXPERT_REVIEW",
    "BUILD_KNOWLEDGE_GRAPH": "REVIEW_KNOWLEDGE_GRAPH",
    "GENERATE_TIMELINE": "REVIEW_TIMELINE_CONFLICT",
    "COLLECT_CORROBORATING_EVIDENCE": "COMPARE_RELATED_EVIDENCE",
    "REVIEW_UNRESOLVED_RELATIONSHIPS": "REVIEW_KNOWLEDGE_GRAPH",
}

GAP_TO_TASK: dict[str, str] = {
    "MISSING_ORIGINAL_FILE": "ACQUIRE_ORIGINAL_EVIDENCE",
    "MISSING_METADATA": "VERIFY_METADATA",
    "MISSING_TIMESTAMP": "VERIFY_METADATA",
    "MISSING_SIGNATURE_VERIFICATION": "RUN_SIGNATURE_VERIFICATION",
    "MISSING_OCR": "REVIEW_OCR",
    "MISSING_AI_ANALYSIS": "MANUAL_EXPERT_REVIEW",
    "MISSING_CORROBORATING_EVIDENCE": "COMPARE_RELATED_EVIDENCE",
    "MISSING_TIMELINE_EVENT": "REVIEW_TIMELINE_CONFLICT",
    "MISSING_GRAPH_RELATIONSHIP": "REVIEW_KNOWLEDGE_GRAPH",
    "MISSING_CHAIN_OF_CUSTODY": "COMPLETE_CHAIN_OF_CUSTODY",
    "MISSING_COMPARISON_TARGET": "COMPARE_RELATED_EVIDENCE",
}
