"""Deterministic policy constants for Phase 9C investigation intelligence."""

from __future__ import annotations

II_ENGINE_VERSION = "9c.1.0"
II_POLICY_VERSION = "1.0"

# Hypothesis type → base confidence when rule fires.
HYPOTHESIS_BASE_CONFIDENCE: dict[str, float] = {
    "LIKELY_DOCUMENT_TAMPERING": 0.78,
    "POSSIBLE_IDENTITY_FRAUD": 0.74,
    "POTENTIAL_DEEPFAKE_MEDIA": 0.76,
    "SIGNATURE_INCONSISTENCY": 0.80,
    "METADATA_MANIPULATION": 0.72,
    "CROSS_EVIDENCE_CORROBORATION": 0.70,
    "TIMELINE_CONFLICT": 0.82,
    "SHARED_DEVICE_USAGE": 0.75,
    "SHARED_IDENTITY_INDICATORS": 0.77,
    "MULTIPLE_EVIDENCE_SAME_EVENT": 0.68,
    "INSUFFICIENT_EVIDENCE": 0.90,
    "CHAIN_OF_CUSTODY_CONCERN": 0.84,
    "MISSING_VERIFICATION": 0.73,
    "INVESTIGATION_COMPLETE": 0.65,
}

GAP_SEVERITY_WEIGHT: dict[str, float] = {
    "HIGH": 1.0,
    "MEDIUM": 0.55,
    "LOW": 0.25,
}

PRIORITY_THRESHOLDS = {
    "HIGH": 0.75,
    "MEDIUM": 0.45,
}

SUPPORT_BOOST = 0.03
SUPPORT_BOOST_CAP = 0.12
CONTRADICT_PENALTY = 0.05
CONTRADICT_PENALTY_CAP = 0.15
PROVENANCE_BOOST = 0.01
PROVENANCE_BOOST_CAP = 0.05
