"""Processing job and artifact domain enumerations."""

from enum import StrEnum


class ProcessingJobType(StrEnum):
    """Supported processing stages in the Phase 4 foundation."""

    INGESTION_INSPECTION = "INGESTION_INSPECTION"
    METADATA_EXTRACTION = "METADATA_EXTRACTION"
    PREVIEW_GENERATION = "PREVIEW_GENERATION"
    FILE_CLASSIFICATION = "FILE_CLASSIFICATION"
    PREPROCESSING = "PREPROCESSING"
    EXTRACTION = "EXTRACTION"
    ANALYSIS = "ANALYSIS"
    COMPARISON = "COMPARISON"
    IMAGE_AI_ANALYSIS = "IMAGE_AI_ANALYSIS"
    DOCUMENT_AI_ANALYSIS = "DOCUMENT_AI_ANALYSIS"
    SIGNATURE_VERIFICATION = "SIGNATURE_VERIFICATION"
    VIDEO_AI_ANALYSIS = "VIDEO_AI_ANALYSIS"
    AUDIO_AI_ANALYSIS = "AUDIO_AI_ANALYSIS"
    MULTIMODAL_FUSION = "MULTIMODAL_FUSION"


class ProcessingJobStatus(StrEnum):
    """Controlled processing job lifecycle states."""

    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ArtifactType(StrEnum):
    """Non-forensic derived artifact categories."""

    PREVIEW = "PREVIEW"
    THUMBNAIL = "THUMBNAIL"
    METADATA = "METADATA"
    CLASSIFICATION = "CLASSIFICATION"
    DERIVATIVE = "DERIVATIVE"
    OCR_RESULT = "OCR_RESULT"
    DOCUMENT_STRUCTURE = "DOCUMENT_STRUCTURE"
    IMAGE_REGIONS = "IMAGE_REGIONS"
    VIDEO_FRAME_INDEX = "VIDEO_FRAME_INDEX"
    AUDIO_STREAM_INFO = "AUDIO_STREAM_INFO"
    VIDEO_FRAME = "VIDEO_FRAME"
    AUDIO_EXTRACT = "AUDIO_EXTRACT"
    TEXT_RESULT = "TEXT_RESULT"
    ELA_RESULT = "ELA_RESULT"
    FORENSIC_HEATMAP = "FORENSIC_HEATMAP"
    FORENSIC_MASK = "FORENSIC_MASK"
    FORENSIC_OVERLAY = "FORENSIC_OVERLAY"
    DETECTOR_OUTPUT = "DETECTOR_OUTPUT"
    COMPARISON_MASK = "COMPARISON_MASK"
    COMPARISON_OVERLAY = "COMPARISON_OVERLAY"
    COMPARISON_SIDE_BY_SIDE = "COMPARISON_SIDE_BY_SIDE"
    COMPARISON_OUTPUT = "COMPARISON_OUTPUT"
    AI_IMAGE_HEATMAP = "AI_IMAGE_HEATMAP"
    AI_IMAGE_MASK = "AI_IMAGE_MASK"
    AI_IMAGE_OVERLAY = "AI_IMAGE_OVERLAY"
    AI_IMAGE_PREDICTION = "AI_IMAGE_PREDICTION"
    AI_DOCUMENT_HEATMAP = "AI_DOCUMENT_HEATMAP"
    AI_DOCUMENT_MASK = "AI_DOCUMENT_MASK"
    AI_DOCUMENT_OVERLAY = "AI_DOCUMENT_OVERLAY"
    AI_DOCUMENT_PREDICTION = "AI_DOCUMENT_PREDICTION"
    AI_SIGNATURE_CROP = "AI_SIGNATURE_CROP"
    AI_SIGNATURE_COMPARISON = "AI_SIGNATURE_COMPARISON"
    AI_SIGNATURE_PREDICTION = "AI_SIGNATURE_PREDICTION"
    AI_VIDEO_FRAME = "AI_VIDEO_FRAME"
    AI_VIDEO_HEATMAP = "AI_VIDEO_HEATMAP"
    AI_VIDEO_MASK = "AI_VIDEO_MASK"
    AI_VIDEO_OVERLAY = "AI_VIDEO_OVERLAY"
    AI_VIDEO_PREDICTION = "AI_VIDEO_PREDICTION"
    AI_VIDEO_TIMELINE = "AI_VIDEO_TIMELINE"
    AI_AUDIO_WAVEFORM = "AI_AUDIO_WAVEFORM"
    AI_AUDIO_SPECTROGRAM = "AI_AUDIO_SPECTROGRAM"
    AI_AUDIO_FEATURES = "AI_AUDIO_FEATURES"
    AI_AUDIO_TIMELINE = "AI_AUDIO_TIMELINE"
    AI_AUDIO_PREDICTION = "AI_AUDIO_PREDICTION"


class EvidenceClassification(StrEnum):
    """Safe broad file categories used to select future processors."""

    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    UNKNOWN = "UNKNOWN"
