apiVersion: v1
kind: Service
metadata:
  name: ai-forge-backend
  namespace: ai-forge
  labels:
    app: ai-forge-backend
spec:
  type: ClusterIP
  selector:
    app: ai-forge-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
