"""Authentication policy constants."""

ENGINE_VERSION = "1.0"
POLICY_VERSION = "1.0"

PASSWORD_MIN_LENGTH = 12
PASSWORD_MAX_LENGTH = 128
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 64
MAX_FAILED_LOGINS = 5
LOCKOUT_MINUTES = 15
IP_MAX_FAILURES = 10
IP_WINDOW_MINUTES = 15
ACCESS_TOKEN_MINUTES = 15
REFRESH_TOKEN_DAYS = 7
REMEMBER_ME_DAYS = 30
SESSION_IDLE_MINUTES = 480
